SWAP_HANDS_ENABLE     = yes
AUTOCORRECT_ENABLE    = yes
CAPS_WORD_ENABLE      = yes
TAP_DANCE_ENABLE      = no
BOOTMAGIC_ENABLE      = yes      # Enable Bootmagic Lite
CUSTOM_UNICODE_ENABLE = yes

BOOTLOADER = tinyuf2

RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = custom

LTO_ENABLE = yes
OPT = fast