SWAP_HANDS_ENABLE     = yes
AUTOCORRECT_ENABLE    = yes
CAPS_WORD_ENABLE      = yes
TAP_DANCE_ENABLE      = no
BOOTMAGIC_ENABLE      = yes
CUSTOM_UNICODE_ENABLE = yes
EEPROM_DRIVER         = i2c
OLED_ENABLE           = no
WPM_ENABLE            = no
DISPLAY_KEYLOGGER_ENABLE = no

POINTING_DEVICE_ENABLE = no
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = yes
RGBLIGHT_DRIVER = custom