SWAP_HANDS_ENABLE     = no
AUTOCORRECT_ENABLE    = yes
CAPS_WORD_ENABLE      = yes
TAP_DANCE_ENABLE      = no
BOOTMAGIC_ENABLE      = yes
CUSTOM_UNICODE_ENABLE = yes
EEPROM_DRIVER         = i2c

# RGB_MATRIX_ENABLE = yes
# RGBLIGHT_ENABLE = yes
# RGBLIGHT_DRIVER = custom