AUTOCORRECT_ENABLE = yes
CAPS_WORD_ENABLE = yes
TAP_DANCE_ENABLE = no
BOOTMAGIC_ENABLE = yes
CUSTOM_UNICODE_ENABLE = yes
EEPROM_DRIVER = i2c
OLED_ENABLE = no
WPM_ENABLE = no
DISPLAY_KEYLOGGER_ENABLE = no

# Enables all custom userspace RGB implementations
# RGB_MATRIX_ENABLE = yes